pipeline:
  tickers: ["AAPL", "BTC-USD", "^GSPC"]
  start_date: "2017-01-01"
  filter_ticker: "^GSPC"
  forecast_horizon: 5

grid_search:
  logistic_regression:
    C: [0.01, 0.1, 1, 10]
    solver: [liblinear, lbfgs]
    max_iter: [200, 500]
  random_forest:
    n_estimators: [50, 100]
    max_depth: [3, 5, 10]
    random_state: [42]
  xgboost:
    n_estimators: [100, 300]
    learning_rate: [0.01, 0.1]
    max_depth: [3, 6]
    random_state: [42]
  svm:
    kernel: [linear, rbf]
    C: [0.1, 1, 10]
    gamma: [scale, auto]

random_search:
  logistic_regression:
    C: [0.001, 0.01, 0.1, 0.5, 1, 5, 10, 50, 100]
    solver: [liblinear, lbfgs, newton-cg, sag, saga]
    max_iter: [100, 200, 500, 1000]
    penalty: [l2]
  random_forest:
    n_estimators: [50, 100, 200, 300, 500]
    max_depth: [null, 3, 5, 10, 15, 20]
    max_features: [sqrt, log2, null]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    bootstrap: [true, false]
    random_state: [42]
  xgboost:
    n_estimators: [50, 100, 200, 300, 500]
    learning_rate: [0.001, 0.01, 0.05, 0.1, 0.2, 0.3]
    max_depth: [3, 4, 5, 6, 7, 8, 9, 10]
    subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
    colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]
    gamma: [0, 0.1, 0.2, 0.3, 0.4]
    reg_alpha: [0, 0.001, 0.01, 0.1, 1]
    reg_lambda: [0, 0.001, 0.01, 0.1, 1]
    random_state: [42]
  svm:
    kernel: [linear, rbf, poly]
    C: [0.1, 1, 10, 100]
    gamma: [scale, auto, 0.01, 0.1, 1]
    degree: [2, 3, 4, 5]
    coef0: [0.0, 0.1, 0.5]
